### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by cody-Valentine** [dyedquartz/mangadex-scraper#6]
Hello, 

I was hoping you could help shed some light on what I'm missing or doing wrong.  
I'm installing via "cargo install mangadex-scraper".  Everything goes well until I get the following error: 
   Compiling serde_urlencoded v0.6.1
   Compiling reqwest v0.10.4
   Compiling mangadex-scraper v0.5.1

error[E0412]: cannot find type `UrlError` in crate `reqwest`
  --> C:\Users\<username>\.cargo\registry\src\github.com-1ecc6299db9ec823\mangadex-scraper-0.5.1\src\main.rs:10:34
   |
10 | fn main() -> Result<(), reqwest::UrlError> {
   |                                  ^^^^^^^^ not found in `reqwest`

error[E0599]: no method named `unwrap` found for opaque type `impl std::future::Future` in the current scope
   --> C:\Users\<username>\.cargo\registry\src\github.com-1ecc6299db9ec823\mangadex-scraper-0.5.1\src\main.rs:152:47
    |
152 |         let mut resp = client.get(url).send().unwrap();
    |                                               ^^^^^^ method not found in `impl std::future::Future`

error[E0599]: no method named `unwrap` found for opaque type `impl std::future::Future` in the current scope
   --> C:\Users\<username>\.cargo\registry\src\github.com-1ecc6299db9ec823\mangadex-scraper-0.5.1\src\main.rs:214:55
    |
214 |                 let mut resp = client.get(url).send().unwrap();
    |                                                       ^^^^^^ method not found in `impl std::future::Future`

error[E0599]: no method named `unwrap` found for opaque type `impl std::future::Future` in the current scope
  --> C:\Users\<username>\.cargo\registry\src\github.com-1ecc6299db9ec823\mangadex-scraper-0.5.1\src\mangadex_api.rs:39:50
   |
39 |     let json: MangaData = client.get(url).send().unwrap().json().unwrap();
   |                                                  ^^^^^^ method not found in `impl std::future::Future`

error[E0599]: no method named `expect` found for opaque type `impl std::future::Future` in the current scope
  --> C:\Users\<username>\.cargo\registry\src\github.com-1ecc6299db9ec823\mangadex-scraper-0.5.1\src\mangadex_api.rs:50:10
   |
50 |         .expect("something went wrong with sending")
   |          ^^^^^^ method not found in `impl std::future::Future`

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0412, E0599.
For more information about an error, try `rustc --explain E0412`.
error: failed to compile `mangadex-scraper v0.5.1`, intermediate artifacts can be found at `C:\Users\<username>\AppData\Local\Temp\cargo-installiu5NiY`

Caused by:
  could not compile `mangadex-scraper`.

If you need any more information or have any input please let me know.  I'll be happy to help the best I can.

**Comment by yerke** [comment]
I got the same issue when I tried to install using `cargo install mangadex-scraper`. It did compile when I cloned the repo, and ran `cargo build`.
