### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by ZapDragon** [dyedquartz/mangadex-scraper#7]
Firstly, I apologize. This is my first time playing with any Rust at all.
I installed the Visual C++ tools and ran `cargo install`

This is the error I am getting.

![image](https://user-images.githubusercontent.com/17253171/81807192-809c6e80-94d2-11ea-9dfb-008d201de8d8.png)

**Comment by Kite1024** [comment]
I've had this same error after doing a "cargo update", it was fixed after doing a "git reset --hard" and then running "cargo run".

**Comment by dyedquartz** [comment]
Crates are outdated, I'll work on updating everything and eventually adding new features

**Comment by dyedquartz** [comment]
#8 updated crates
